name: Weekly Campaigns
on:
  schedule:
    - cron: '0 9 * * 6' # 9 AM GMT every Saturdays
  workflow_dispatch:

jobs:
  segmented-users:
    name: 'Get user based on segments'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --silent --prefer-offline

      - name: Run executable script
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          DB_PORT: ${{ secrets.HOST_NAME }}
          DB: ${{ secrets.DB }}
          CA_CERT: ${{ secrets.CA_CERT }}

        run: yarn build && yarn start
